name: Docker CI/CD

on:
  push:
    branches:
      - main
      - beta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image (latest)
      if: github.ref_name == 'main'
      uses: docker/build-push-action@v4
      with:
          context: .
          push: true
          tags: elap1/mungbot:latest
    
    - name: Build and push Docker image (beta)
      if: github.ref_name == 'beta'
      uses: docker/build-push-action@v4
      with:
          context: .
          push: true
          tags: elap1/mungbot:beta

    - name: Deploy updated container
      if: github.ref_name == 'main'
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NYJ_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no -p 30000 ${{ secrets.SERVER_USER }}@${{ secrets.NYJ_SERVER_IP }} << 'EOF'
          cd docker_mung
          sudo docker pull elap1/mungbot:latest
          sudo docker stop mungR || true
          sudo docker rm mungR || true
          sudo docker run -d \
             --name mungR \
             --restart on-failure \
             -v $(pwd)/.env:/usr/src/app/.env \
             -v $(pwd)/.env:/usr/src/app/app_command/.env \
             -v $(pwd)/config.json:/usr/src/app/data/config/config.json \
             -v $(pwd)/private.json:/usr/src/app/data/security/private.json \
             elap1/mungbot:latest
          EOF
      
    - name: Deploy updated beta container
      if: github.ref_name == 'beta'
      run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
          cd docker_mung
          sudo docker pull elap1/mungbot:beta
          sudo docker stop mungR_B || true
          sudo docker rm mungR_B || true
          sudo docker run -d \
             --name mungR_B \
             --restart on-failure \
             -v $(pwd)/.env:/usr/src/app/.env \
             -v $(pwd)/.env:/usr/src/app/app_command/.env \
             -v $(pwd)/config.json:/usr/src/app/data/config/config.json \
             -v $(pwd)/private.json:/usr/src/app/data/security/private.json \
             elap1/mungbot:beta
          EOF
    
